version: '3.4'

networks:
    thomasgregchallengeapp:

services:  
  thomasgregchallengedb:
    container_name: thomasgregchallengedb
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Q2w3e4r
      - MSSQL_SA_PASSWORD=1Q2w3e4r      
      - MSSQL_PID=Express
    networks:
       - thomasgregchallengeapp
    volumes:  
      - sqlserver_data:/var/opt/mssql  
  thomasgregchallengeapi:
    container_name: thomas-greg-challenge-api
    image: ${DOCKER_REGISTRY-}thomasgregchallengeapi
    build:
      context: .
      dockerfile: ThomasGregChallenge/Dockerfile
    ports:
      - 8085:85
      - 56321:445
    depends_on:
      - thomasgregchallengedb
    environment:
      - DB_HOST=thomasgregchallengedb
      - DB_NAME=thomasgregchallengedb
      - DB_SA_USER_ID=sa
      - DB_SA_PASSWORD=1Q2w3e4r
      - DB_PORT=1433
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:445;http://+:85   
    networks:
      - thomasgregchallengeapp
  thomasgregchallenge.ui:
    container_name: thomas-greg-challenge-ui
    image: ${DOCKER_REGISTRY-}thomasgregchallengeui
    build:
      context: .
      dockerfile: ThomasGregChallenge.UI/Dockerfile
    ports:
      - 8081:81
      - 56322:444
    depends_on:
      - thomasgregchallengeapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:444;http://+:81
    networks:
      - thomasgregchallengeapp
volumes:
  sqlserver_data: 
